### ISSUE TITLE
**Universal-Manager!**

### ISSUE THREAD

**Issue by SuperSaiyajinStackZ** [Universal-Team/Universal-Manager#14]
This will be the new Name, after the Rewrite is done. 

Planned Things : 

- FTP Client.
- File Manager.
- Updater.
And a few other Things.

;)

**Comment by SuperSaiyajinStackZ** [comment]
**Update**

Currently, the Buttons are working and a few Screens are done. 

Also The Music Player works, but it crashes currently, when you want to Play another file or when the Song is done.

**Comment by SuperSaiyajinStackZ** [comment]
**Update**

The Music Player is now finally fixed. 😛

**Comment by SuperSaiyajinStackZ** [comment]
**Update**

The Download Screen and the Music Player are finally complete done in a bit! 😛 The next work then would be probably : 

- The FTP Screen.

**Comment by SuperSaiyajinStackZ** [comment]
so umm.. the Citro2D Rewrite is done and it optimize everything a lot! The VoltLib has taken a lot of GPU/CPU, which was not really good at all. There are still Issues like the Settings Screen. 😛

**Comment by SuperSaiyajinStackZ** [comment]
The Rewrite is done now, so I close this Issue!

**Comment by legoj15** [comment]
Nice work!

**Comment by SuperSaiyajinStackZ** [comment]
Thanks! 😛
