### ISSUE TITLE
License violation.

### ISSUE THREAD

**Issue by joel16** [Universal-Team/Universal-Manager#26]
Hi, I came across this a while ago and noticed my code for SDL_helper, and other stuff from 3dshell being used however I noticed you're making your own copyright claim for the switch code: https://github.com/Universal-Team/Universal-Manager/blob/master/switch/include/SDL_helper.h#L2 which I don't think is legal. Correct me if I'm wrong but you cannot make your own claim on something that's already copyrighted to GLPv3.

I'm not stopping you from using it anything, but I thought I'd let you know.

**Comment by SuperSaiyajinStackZ** [comment]
Thank you for letting me know. For 3DShell, I gave credits inside the 3ds folder.

Do you noticed any other Things from 3DShell, I Need to License or from the switch stuff? If yes, please let me know. Thanks!

I will fix this With SDL_helper.h with the next commits!

**Comment by joel16** [comment]
Nope it was just that, thanks and good luck with your project.

**Comment by SuperSaiyajinStackZ** [comment]
No problem and thank you! 😄
