### ISSUE TITLE
Performance issues in various menus

### ISSUE THREAD

**Issue by Kodtiz3D** [Universal-Team/Universal-Manager#28]
**Describe the bug**
In the Scripts menu, when scripts are on screen it tanks the FPS.

**To Reproduce**
Download the scripts from the Updater page with `Extra - Scripts`

**Expected behavior**
Consistent performance/FPS when idling and in navigating.

**Console (please complete the following information):**
  - 3DS
  - Luma 10.0.1
  - UM Version 3.1 Nightly (Commit hash unknown)

**Comment by SuperSaiyajinStackZ** [comment]
This should be fixed with the Latest Commit : https://github.com/Universal-Team/Universal-Manager/commit/8039ccecf1447b5d40519e60cc9a4f01ef021780

Can you test the latest Nightly and confirm that? :)

**Comment by Kodtiz3D** [comment]
While performance has most certainly improved, the speed of the background is noticeably slower when compared to the main menu. Similar slowness also happens in the `Filemenu` screen. I also noticed significant slowdowns in the `Playlist` section of the `Music Player Menu`. This was tested using Nightly 5d154f1a59d629514515476572d33a9b0b926733
I do not know if the slower BG speed is intentional or not but it is something I noticed.

**Comment by Epicpkmn11** [comment]
iirc VoltZ has it waiting 2 vblanks instead of one in lists currently to make the cursor usably slow (the 3DS doesn't have `keysDownRepeat()` like the DS), but this also slows the background, I assume that could be fixed by adding some kinda key wait variable like
```cpp
// In a global scope
int keyDelay = 0;
---
// In the main loop (probably by wherever the vblank wait is)
if(keyDelay > 0) keyDelay--;
---
// When checking the key
if(held & KEY_DOWN && keyDelay == 0) {
    keyDelay = 3;
    // Other code
}
```
or you could do like libnds's keysDownRepeat https://github.com/devkitPro/libnds/blob/105d4943dbac8f2bd99a47b22cd3ed48f96af083/source/arm9/keys.c#L47

**Comment by Kodtiz3D** [comment]
Makes sense. As for the performance in the `Playlists`, it's significantly lower than 30fps as I can see the individual frames. Or it's just jittery. Can't tell.

**Comment by Epicpkmn11** [comment]
The playlist screen is scanning the SD every frame, so that's why it's so slow
musicPlayerScreen.cpp (Line 537)
```cpp
	if(dirChanged) {
		char startPath[PATH_MAX];
		getcwd(startPath, PATH_MAX);
		chdir("sdmc:/Universal-Manager/playlists/");
		getDirectoryContents(plsts);
		chdir(startPath);
	}
```
should be
```cpp
	if(dirChanged) {
		dirChanged = false;
		char startPath[PATH_MAX];
		getcwd(startPath, PATH_MAX);
		chdir("sdmc:/Universal-Manager/playlists/");
		getDirectoryContents(plsts);
		chdir(startPath);
	}
```

**Comment by Kodtiz3D** [comment]
Tested using Nightly ae8a0def1f0b066ec39391a872219c8f56bfa25c
All screens with the performance issues are now fluid compared to the main menu, thanks!
